### ISSUE TITLE
Analytics & Telemetry concerns are mixed together in analytics plugin

### ISSUE THREAD

**Issue by vishal-kr-barnwal** [vyuh-tech/vyuh#18]
In Analytics Plugin, current Analytics and telemetry are mixed together.

These should be separated as if any one is adding Analytics Plugin like GA / Adobe Omni - it doesn't need to have traces and similarly for Sentry, NewRelic, etc. they don't need to have events.

We already have log plugin separately, which can be expanded further to contain traces and spans to evolve into telemetry plugin.

This will create a proper separation of concerns for User Analytics and RUM/telemetry events.

**Comment by vishal-kr-barnwal** [comment]
PR Raised https://github.com/vyuh-tech/vyuh/pull/34

**Comment by pavanpodila** [comment]
this is now addressed in #36 and inspired from #34
