### ISSUE TITLE
There should be a PortableText that doesn't use ListView, for better sliver support

### ISSUE THREAD

**Issue by andreasmpet** [vyuh-tech/vyuh#20]
When trying to use PortableText within a sliver-environment, it won't work because there is a regular ListView in there. This causes issues with computeDryLayout not being supported on a shrinkwrapped listview, and again, for the widget to fail to render.

My quick super dirty workaround for my problem was the code below.
Note that I should probably forward a bunch of Column-related properties like crossAxisAlignment etc, but this is just for illustrative purposes.

```
class ColumnPortableText extends StatelessWidget {
  final List<PortableBlockItem> blocks;

  const ColumnPortableText({super.key, required this.blocks});

  @override
  Widget build(BuildContext context) {
    final blockWidgets = blocks.map(
      (item) {
        final type = item.blockType;

        final builder = PortableTextConfig.shared.blocks[type];
        if (builder == null) {
          return ErrorView(message: 'Missing builder for block "$type"');
        }

        return builder(context, item);
      },
    );

    return Column(children: blockWidgets.toList());
  }
}
```

**Comment by pavanpodila** [comment]
I think we will need a SliverPortableText to make this more bulletproof. Treating this as an enhancement

**Comment by pavanpodila** [comment]
BTW, what is your parent widget @andreasmpet ? Could you share that please to understand if its being used inside a `CustomScrollView` or otherwise

**Comment by pavanpodila** [comment]
On a separate note, have you tried using the [SliverToBoxAdapter](https://api.flutter.dev/flutter/widgets/SliverToBoxAdapter-class.html) as a wrapper around the `PortableText` Widget ?

**Comment by andreasmpet** [comment]
> BTW, what is your parent widget @andreasmpet ? Could you share that please to understand if its being used inside a `CustomScrollView` or otherwise


Hey! Thanks for the reply! Here's some context around my use case.

I have SliverResizingHeader at the top of a CustomScrollView wrapped in this MultiSliver from the sliver_tools package.

_BannerStrip has a SingleChildScroolView in it for it to be gracefully scaled down and scrolled out of view. Without the scrollview the view overflows as it is scaled down. I've also found that reversing the scroll view provides the illusion that it is scrolled out of view seemlessly.

```
    return MultiSliver(
      children: [
        if (bannerStrip1 != null)
          SliverResizingHeader(
            child: _BannerStrip(bannerTextBlocks: bannerStrip1, backgroundColor: context.colorScheme.onPrimary),
          ),
        if (bannerStrip2 != null)
          SliverResizingHeader(
              child: _BannerStrip(bannerTextBlocks: bannerStrip2, backgroundColor: context.colorScheme.secondary)),
        if (bannerStrip1 != null || bannerStrip2 != null) GSpacing.vertical.s16(),
        SliverSafeArea(sliver: elementContent),
      ],
    );
```


```

class _BannerStrip extends StatelessWidget {
  final List<TextBlockItem> bannerTextBlocks;
  final Color backgroundColor;

  const _BannerStrip({super.key, required this.bannerTextBlocks, required this.backgroundColor});

  @override
  Widget build(BuildContext context) {
    return Container(
      clipBehavior: Clip.antiAlias,
      decoration: BoxDecoration(color: backgroundColor),
      child: SingleChildScrollView(
        physics: const NeverScrollableScrollPhysics(),
        reverse: true,
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          mainAxisAlignment: MainAxisAlignment.end,
          children: [
            GPadding.vertical.s8(
              child: GPadding.pageMargins(
                child: ColumnPortableText(
                  blocks: bannerTextBlocks,
                ),
              ),
            )
          ],
        ),
      ),
    );
  }
}
```

> On a separate note, have you tried using the [SliverToBoxAdapter](https://api.flutter.dev/flutter/widgets/SliverToBoxAdapter-class.html) as a wrapper around the PortableText Widget ?

No, but as you see it is already wrapped in a normal widget, that is passed as a child to the SliverResizingHeader

**Comment by pavanpodila** [comment]
Given the use case you have I think we could do just a `PortableTextBuilder` like widget that will call an `containerBuilder` to generate the wrapper for the individual text blocks? Will that help. In your case, it will be a wrapper that creates the `Column` widget.

How does that sound? Just thinking aloud for a more general solution . @andreasmpet

**Comment by pavanpodila** [comment]
this has been fixed with the introduction of a listBuilder that can be optionally supplied to PortableText. The default one uses a ListView.builder, but you are free to use your own, such as Column for building up the list. This should be useful in sliver environments as well.

Closing it for now. Feel free to open it up again if this is still inadequate @andreasmpet

**Comment by andreasmpet** [comment]
Amazing! Thanks for the quick turnaround on this!
