### ISSUE TITLE
Enable Extensions for Content Items

### ISSUE THREAD

**Issue by rajan-nonstopio** [vyuh-tech/vyuh#22]
Allow content items to be extensible at the consumer level. This enhancement will enable specific content items to support additional features such as theming or coachmarks, providing developers with greater flexibility and customization options.

For example, a particular content item could be extended to include a custom theme or interactive coachmarks.

**Comment by pavanpodila** [comment]
This is now available in the latest version as a Modifier. You can read more about it [here](https://docs.vyuh.tech/guides/cms/custom-modifier/).
