### ISSUE TITLE
Localisation at content item level

### ISSUE THREAD

**Issue by msp98** [vyuh-tech/vyuh#23]
As a user, I should be able to see a particular component in my local language based on either my geographical location or the language I have configured in my app settings.

**Example Scenario:**

**Geographical Location-Based Localization:**
- If a user resides in France, the content items should be displayed in French.
- If a user resides in Japan, the content items should be displayed in Japanese.

**User-Configured Language:**
- If a user has set their preferred language to Spanish in the app settings, all content items should be displayed in Spanish, regardless of their geographical location.

**Comment by pavanpodila** [comment]
This is now available in the latest version as a Modifier. Feel free to experiment with your own custom Localization Modifier.

You can read more about it [here](https://docs.vyuh.tech/guides/cms/custom-modifier/).
