### ISSUE TITLE
Add Category-Level Extensions for Common Themes, Layouts, and Coachmarks

### ISSUE THREAD

**Issue by rajan-nonstopio** [vyuh-tech/vyuh#24]
Introduce category-level extensions to apply common themes, layouts, and coachmarks across multiple content items. This feature will allow developers to define and manage consistent styling, layout configurations, and user guidance elements at a higher level, ensuring uniformity and reducing redundancy.

For example, a category of content items can share a common theme or layout, and have coachmarks applied uniformly, enhancing the user experience and simplifying maintenance.

**Comment by pavanpodila** [comment]
This is now available in the latest version as a Modifier. You can read more about it [here](https://docs.vyuh.tech/guides/cms/custom-modifier/).
