### ISSUE TITLE
Add Lifecycle Event Hooks for Content Items

### ISSUE THREAD

**Issue by Sourav-Sonkar** [vyuh-tech/vyuh#25]
An enhancement to the Vyuh framework to support lifecycle event hooks for content items. This feature would allow developers to register callbacks for specific lifecycle events such as initialisation, disposal, and dependency changes. This can be particularly useful for managing resources, performing cleanup tasks, and responding to changes in dependencies.

**Comment by pavanpodila** [comment]
this is now available in the latest commits...You can subscribe to an event in the feature-init with `vyuh.event.on<Event>(listener)` where listener will be a callback function that contains the event. The method also returns a subscription which can be disposed later to cleanup.

```dart
final sub = vyuh.event.on<SystemReadyEvent>(() => vyuh.log?.d('We are ready!'));

// at a later point, dispose
sub();
```

To fire events, which are type safe, use:
`vyuh.event.emit(MyEvent())` where `MyEvent` extends the `VyuhEvent` class.
