### ISSUE TITLE
Getting Sanity related issue while creating project with vyuh cli (vyuh create project <project_name>)

### ISSUE THREAD

**Issue by kartikkanteti** [vyuh-tech/vyuh#28]
<img width="563" alt="Screenshot 2024-10-22 at 2 12 13 PM" src="https://github.com/user-attachments/assets/9afad407-c793-4770-884b-3791ddb96a9d">

**Comment by pavanpodila** [comment]
Thanks for reporting @kartikkanteti. We have just pushed an update to the CLI that fixes the above with a pre-condition check. We also added this in our [docs](https://docs.vyuh.tech/intro/cli/).

Please update your vyuh cli with `vyuh update` and try again with better checks.

Closing for now.
