### ISSUE TITLE
Conflict .DS_Store issue appearing while creating new project, schema or feature using vyuh_cli

### ISSUE THREAD

**Issue by kartikkanteti** [vyuh-tech/vyuh#29]
![Screenshot 2024-10-23 at 12 31 44 PM](https://github.com/user-attachments/assets/6f6990f5-568b-4f89-8eac-c9c5df329f30)

**Comment by pavanpodila** [comment]
This has been fixed now ... thanks for reporting @kartikkanteti ...there was a stray .DS_Store directory inside the bricks folder which has now been removed. You should not see this error any more... 

Please try with the latest version `0.0.4+6` using `vyuh update`
