### ISSUE TITLE
nice Package for flutter to render the UI  from sanity, it would be better even if you manage the images  and add an option to add custom widget for lineItem

### ISSUE THREAD

**Issue by chenna8464** [vyuh-tech/vyuh#5]
currently, we have these types  
enum ListItemType { bullet, square, number }
 if someone wants to add their own widget here, they can't

**Comment by pavanpodila** [comment]
Good point. However these are dictated by the PortableText specification and there is no option to extend the list item rendering over there. One option is to expose custom renderer for the particular list item

**Comment by pavanpodila** [comment]
With this commit, we now have the ability to customize the bullet renderer by passing it as an option to `PortableTextConfig`. You can see it in this commit: https://github.com/vyuh-tech/vyuh/commit/9b2ea4c3ec8d71f103dcfecc881437832f0a48c5
